# vim: set et ts=2 ss=2 sw=2 :

title: "/* TODO: Replace with clever title */"
author: "Emil Ohlsson"
email: kotte@kottland.net
description: >
    Occasional posts about programming... I think... Let's see
baseurl: ""
url: "https://emilohlsson.github.io"
github_username:  EmilOhlsson

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
