title: "/* TODO: Replace with clever title */"
email: kotte@kottland.net
description: >
    Occasional posts about programming... I think... Let's see
baseurl: ""
url: "https://elektrokotte.github.io"
twitter_username: elektrokotte
github_username:  elektrokotte

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
